Baudrate:
  9600
Timeout:
  10
Ports:
  - /dev/ttyACM0
  - /dev/ttyACM1
State:
  WHOAMI:
    ''
  Start: 
    '1'
  Duration: 
    '1'
  Birthtime: 
    '1'
  Velocity:
    '2'
  Pose:
    '2'
  IMU:
    '2'