joint_motor_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints: 
        - prop_fr_joint
        - prop_fl_joint
        - prop_br_joint
        - prop_bl_joint

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
gazebo_ros_control:
    pid_gains:
        prop_fr_joint:
            p: 100.0
            i: 1.0
            d: 10.0
        prop_fl_joint: 
            p: 100.0
            i: 1.0
            d: 10.0
        prop_br_joint: 
            p: 100.0
            i: 1.0
            d: 10.0
        prop_bl_joint: 
            p: 100.0
            i: 1.0
            d: 10.0