joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

motor1:
  joint: rotor_0_joint
  pid:
    {p: 1, i: 0, d: 1}
  type: effort_controllers/JointVelocityController

motor2:
  joint: rotor_1_joint
  pid:
    {p: 1, i: 0, d: 1}
  type: effort_controllers/JointVelocityController

motor3:
  joint: rotor_2_joint
  pid:
    {p: 1, i: 0, d: 1000}
  type: effort_controllers/JointVelocityController

motor4:
  joint: rotor_3_joint
  pid:
    {p: 1, i: 0, d: 1}
  type: effort_controllers/JointVelocityController

