// Generated by gencpp from file arman_controller/ArmanDriverRequestRequest.msg
// DO NOT EDIT!


#ifndef ARMAN_CONTROLLER_MESSAGE_ARMANDRIVERREQUESTREQUEST_H
#define ARMAN_CONTROLLER_MESSAGE_ARMANDRIVERREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arman_controller
{
template <class ContainerAllocator>
struct ArmanDriverRequestRequest_
{
  typedef ArmanDriverRequestRequest_<ContainerAllocator> Type;

  ArmanDriverRequestRequest_()
    : joint0(0.0)
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)  {
    }
  ArmanDriverRequestRequest_(const ContainerAllocator& _alloc)
    : joint0(0.0)
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)  {
  (void)_alloc;
    }



   typedef float _joint0_type;
  _joint0_type joint0;

   typedef float _joint1_type;
  _joint1_type joint1;

   typedef float _joint2_type;
  _joint2_type joint2;

   typedef float _joint3_type;
  _joint3_type joint3;

   typedef float _joint4_type;
  _joint4_type joint4;





  typedef boost::shared_ptr< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmanDriverRequestRequest_

typedef ::arman_controller::ArmanDriverRequestRequest_<std::allocator<void> > ArmanDriverRequestRequest;

typedef boost::shared_ptr< ::arman_controller::ArmanDriverRequestRequest > ArmanDriverRequestRequestPtr;
typedef boost::shared_ptr< ::arman_controller::ArmanDriverRequestRequest const> ArmanDriverRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator1> & lhs, const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint0 == rhs.joint0 &&
    lhs.joint1 == rhs.joint1 &&
    lhs.joint2 == rhs.joint2 &&
    lhs.joint3 == rhs.joint3 &&
    lhs.joint4 == rhs.joint4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator1> & lhs, const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arman_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5075703135afe07e4798ec5d505e6971";
  }

  static const char* value(const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5075703135afe07eULL;
  static const uint64_t static_value2 = 0x4798ec5d505e6971ULL;
};

template<class ContainerAllocator>
struct DataType< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arman_controller/ArmanDriverRequestRequest";
  }

  static const char* value(const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 joint0\n"
"float32 joint1\n"
"float32 joint2\n"
"float32 joint3\n"
"float32 joint4\n"
;
  }

  static const char* value(const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint0);
      stream.next(m.joint1);
      stream.next(m.joint2);
      stream.next(m.joint3);
      stream.next(m.joint4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmanDriverRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arman_controller::ArmanDriverRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint0: ";
    Printer<float>::stream(s, indent + "  ", v.joint0);
    s << indent << "joint1: ";
    Printer<float>::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    Printer<float>::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    Printer<float>::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    Printer<float>::stream(s, indent + "  ", v.joint4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMAN_CONTROLLER_MESSAGE_ARMANDRIVERREQUESTREQUEST_H
