// Generated by gencpp from file arman_controller/ArmanDriverRequestResponse.msg
// DO NOT EDIT!


#ifndef ARMAN_CONTROLLER_MESSAGE_ARMANDRIVERREQUESTRESPONSE_H
#define ARMAN_CONTROLLER_MESSAGE_ARMANDRIVERREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arman_controller
{
template <class ContainerAllocator>
struct ArmanDriverRequestResponse_
{
  typedef ArmanDriverRequestResponse_<ContainerAllocator> Type;

  ArmanDriverRequestResponse_()
    : status(0)  {
    }
  ArmanDriverRequestResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ArmanDriverRequestResponse_

typedef ::arman_controller::ArmanDriverRequestResponse_<std::allocator<void> > ArmanDriverRequestResponse;

typedef boost::shared_ptr< ::arman_controller::ArmanDriverRequestResponse > ArmanDriverRequestResponsePtr;
typedef boost::shared_ptr< ::arman_controller::ArmanDriverRequestResponse const> ArmanDriverRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator1> & lhs, const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator1> & lhs, const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arman_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x581cc55c12abfc21ULL;
  static const uint64_t static_value2 = 0x9e446416014f6d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arman_controller/ArmanDriverRequestResponse";
  }

  static const char* value(const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 status\n"
"\n"
;
  }

  static const char* value(const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmanDriverRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arman_controller::ArmanDriverRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARMAN_CONTROLLER_MESSAGE_ARMANDRIVERREQUESTRESPONSE_H
